version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "patooti-scale:1:1,sd-covid-status:1:1,sms-notification:1:1;streams-plaintext-input:1:1,streams-wordcount-output:1:1compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
